<?xml version='1.0'?>
<robot name="robot_project" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find description_robot_ipsa)/urdf/material.xacro"/>
  <xacro:include filename="$(find description_robot_ipsa)/urdf/transmission.xacro"/>
  <xacro:include filename="$(find description_robot_ipsa)/urdf/robot_project.gazebo"/>

  <xacro:property name="wheelRadius" value="0.05"/>

  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_height" value="0.35"/>

  <xacro:property name="arm1_width" value="0.14"/>
  <xacro:property name="arm1_length" value="0.4"/>

  <xacro:property name="arm2_width" value="0.06"/>
  <xacro:property name="arm2_length" value="0.1"/>

  <xacro:property name="arm3_width" value="0.06"/>
  <xacro:property name="arm3_length" value="0.1"/>

  <xacro:property name="end_effector_width" value="0.07"/>
  <xacro:property name="end_effector_length" value="0.095"/>

  <xacro:macro name="box_inertial" params="mass width height depth">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12 * (height*height + depth*depth)}"
        iyy="${mass / 12 * (width*width + depth*depth)}"
        izz="${mass / 12 * (width*width + height*height)}"
        ixy="0" iyz="0" ixz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="default_origin" params="z">
    <origin xyz="0 0 ${z}" rpy="0 0 0"/>
  </xacro:macro>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </xacro:macro>
  <!-- ***************************************** -->
  <link name="base_footprint"/>
  


  <link name="base_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
        <mesh filename="package://description_robot_ipsa/meshes/base.stl" scale = "0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
     <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
     <geometry>
      <mesh filename="package://description_robot_ipsa/meshes/base.stl" scale = "0.001 0.001 0.001"/>
     </geometry>
    </collision>
    <xacro:box_inertial mass="10" width="${base_width}" height="${base_height}" depth="${base_width}"/>
  </link>

    <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheelRadius}"/>
  </joint>
  
  
<xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <mesh filename="package://description_robot_ipsa/meshes/wheel.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
          <geometry>
              <sphere radius="${wheelRadius}"/>
          </geometry>
          <xacro:default_origin z="0"/>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>

    <joint name="base_to_${prefix}_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <origin xyz="0 ${reflect} 0" rpy="0 0 0" />
        <axis xyz="1 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel prefix="right" reflect="0.195" />
  <xacro:wheel prefix="left" reflect="-0.195" />

  <link name="front_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheelRadius}"/>
      </geometry>
      <origin xyz="0 0 0"/> <!-- -0.05 -->
      <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheelRadius}"/>
        </geometry>
        <xacro:default_origin z="0"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="base_link_to_front_wheel" type="fixed">
      <parent link="base_link"/>
      <child link="front_wheel"/>
      <origin xyz="${base_width/2.5} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
  </joint>

    <link name="back_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheelRadius}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheelRadius}"/>
        </geometry>
        <xacro:default_origin z="0"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="base_link_to_back_wheel" type="fixed">
      <parent link="base_link"/>
      <child link="back_wheel"/>
      <origin xyz="-${base_width/2.5} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
  </joint>

  <link name="arm1">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        <geometry>
        <mesh filename="package://description_robot_ipsa/meshes/arm1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="red"/>
        </visual>
        <collision>
     <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
     <geometry>
      <mesh filename="package://description_robot_ipsa/meshes/arm1.stl" scale="0.001 0.001 0.001"/>
     </geometry>
    </collision>
     <xacro:box_inertial mass="0.5" width="${arm1_width}" height="${arm1_length}" depth="${arm1_width}"/>
  </link>

  <joint name="base_link_to_arm1" type="revolute">
    <parent link="base_link"/>
    <child link = "arm1"/>
    <origin xyz="0 0 0.25" rpy="0 0 0"/>
    <axis xyz ="0 1 0"/>
    <limit effort="100" lower="${-1.3}" upper="${1.3}" velocity="5"/>
  </joint> -->

 
  <link name="arm2">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://description_robot_ipsa/meshes/arm2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="orange"/>
    </visual>
    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
      <mesh filename="package://description_robot_ipsa/meshes/arm2.stl" scale="0.001 0.001 0.001"/>
     </geometry>
    </collision>
     <xacro:box_inertial mass="0.3" width="${arm2_width}" height="${arm2_length}" depth="${arm2_width}"/>
  </link>

  <joint name="arm1_to_arm2" type="revolute">
    <parent link="arm1"/>
    <child link = "arm2"/>
    <origin xyz="0 0 0.43" rpy="0 0 0"/>
    <axis xyz ="0 1 0"/>
    <limit effort="60" lower="${-pi/2}" upper="${pi/2}" velocity="2"/>
  </joint>

    <link name="arm2bis">   
    <xacro:box_inertial mass="0.3" width="${arm3_width}" height="${arm3_length}" depth="${arm3_width}"/>
 </link>


  <joint name="arm2_to_arm2bis" type="revolute">
    <parent link="arm2"/>
    <child link = "arm2bis"/>
    <origin xyz="0 0 0.245" rpy="0 0 0"/>
    <axis xyz ="0 1 0"/>
    <limit effort="50" lower="${-pi/4}" upper="${pi/4}" velocity="1.5"/>
  </joint>

    
  <link name="arm3">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        <geometry>
            <mesh filename="package://description_robot_ipsa/meshes/arm3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="green"/>
    </visual>
    <collision>
     <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
     <geometry>
      <mesh filename="package://description_robot_ipsa/meshes/arm3.stl" scale="0.001 0.001 0.001"/>
     </geometry>
    </collision>
     <xacro:box_inertial mass="0.3" width="${arm3_width}" height="${arm3_length}" depth="${arm3_width}"/>
  </link>
<joint name="arm2bis_to_arm3" type="revolute">
    <parent link="arm2bis"/>
    <child link = "arm3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz ="1 0 0"/>
    <limit effort="50" lower="${-pi/4}" upper="${pi/4}" velocity="1.5"/>
  </joint>

  <link name="end_effector">
    <visual>
        <origin xyz="0 0 0" rpy = "0 0 0"/>
        <geometry>
            <mesh filename="package://description_robot_ipsa/meshes/arm4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
      <mesh filename="package://description_robot_ipsa/meshes/arm4.stl" scale="0.001 0.001 0.001"/>
     </geometry>
    </collision>
     <xacro:box_inertial mass="0.1" width="${end_effector_width}" height="${end_effector_length}" depth="${end_effector_width}"/>
  </link>

  <joint name="arm3_to_end_effector" type="prismatic">
    <parent link="arm3"/>
    <child link = "end_effector"/>
    <origin xyz="0 0 0.19" rpy="0 0 0"/>
    <axis xyz ="0 1 0"/>
    <limit effort="1000" lower="-0.01" upper="0.03" velocity="1.5"/>
  </joint>
  

</robot>
