robot_project:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_arm1
    pid: {p: 500, i: 0.35, d: 30.0}
  arm2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_to_arm2
    pid: {p: 500, i: 0, d: 0}

  arm2bis_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_to_arm2bis
    pid: {p: 300, i: 0, d: 0}

  arm3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2bis_to_arm3
    pid: {p: 300, i: 0, d: 0}

  end_effector_effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm3_to_end_effector
    pid: {p: 1200, i: 0, d: 0}
